num_gpus: 2
train:
  enable: True
  checkpoint_metric: val/mAP
  checkpoint_mode: max
  batch_size: 8
val:
  batch_size: 8
test:
  enable: False
solver:
  num_epochs: 150
  lr: 15e-3
  weight_decay: 1e-5
  warmup_epochs: 5
data:
  train_anno_path: data/ek/annotations/train.json
  val_anno_path: data/ek/annotations/val.json
  test_anno_path: data/ek/annotations/val.json
  output_segments: [0, 1]
  input_segments: [0, 1]
  input_from_annotated_segments: True
  strict: False
  image:
    fps: 60.0
    base_path: /gpfs/data/csun45/cfu17/GLIP_temp/output_CLIP_img_embedding_ek55_frames_all
    split: 0
    num_images_per_segment: 4
    input_segments: [0, 1]
multicls:
  enable: True
  train_Ks: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  val_Ks: [.25, .50, .75]
  many_shot_path: 'data/ek/annotations/EPIC_many_shot_verbs.csv'
model:
  loss_fn: MultiClassBCELoss
  num_classes: [125, 5]
  base_feat_size: 1024
  img_feat_size: 768
  pte:
    num_layers: 1
    enc_dropout: 0.1
    pos_dropout: 0.1
  loss_wts_temporal: [1.]
  num_actions_to_predict: 1
